name: Publish to Docker

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create .env file
        # Set All Environment Variables to .env file
        run: |
          echo "NODE_ENV=${{vars.NODE_ENV}}" >> .env
          echo "PORT=${{vars.PORT}}" >> .env
          echo "DB_URI=${{vars.DB_URI}}" >> .env
          echo "DB_URI_PROD=${{vars.DB_URI_PROD}}" >> .env
          echo "DEFAULT_STUDENT_PASS=${{vars.DEFAULT_STUDENT_PASS}}" >> .env
          echo "DEFAULT_FACULTY_PASS=${{vars.DEFAULT_FACULTY_PASS}}" >> .env
          echo "DEFAULT_ADMIN_PASS=${{vars.DEFAULT_ADMIN_PASS}}" >> .env
          echo "BCRYPT_SALT_ROUNDS=${{vars.BCRYPT_SALT_ROUNDS}}" >> .env
          echo "JWT_SECRET=${{vars.JWT_SECRET}}" >> .env
          echo "JWT_EXPIRES_IN=${{vars.JWT_EXPIRES_IN}}" >> .env
          echo "JWT_REFRESH_SECRET=${{vars.JWT_REFRESH_SECRET}}" >> .env
          echo "JWT_REFRESH_EXPIRES_IN=${{vars.JWT_REFRESH_EXPIRES_IN}}" >> .env

      - name: Login to Docker
        run: echo "${{secrets.DOCKER_ACCESS_TOKEN}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/university_auth:latest

      - name: Push Docker Image
        run: docker push ${{secrets.DOCKER_USERNAME}}/university_auth:latest
